### ISSUE TITLE
[BUG] Reagent counts not updating when you buy more from the vendor/restock from bank/receive from others.

### ISSUE THREAD

**Issue by padmanek** [KaybeHud/Klappa#2]
As title says. You need to reload UI for it to update. But if you delete/buy more reagents/restock from bank it does not update the number. It's the same for consumables. If you take fx. Mana Potions from bank it will not update the number.

**Comment by KaybeHud** [comment]
thank you for your feedback.
please try again, should be fixed now.

**Comment by padmanek** [comment]
It looks like it's fixed. Thank you :)
